default: &default
  adapter: postgresql
  username: postgres # TODO
  password: postgres # TODO
  encoding: unicode
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: microverse
  host: localhost

test:
  <<: *default
  database: microverse
  host: localhost

production:
  <<: *default
  pool: 10
  database: <%= ENV['DATABASE_NAME'] %>
  host: <%= ENV['DATABASE_HOST'] %>
